#!/usr/bin/env python3
"""Regenerate Highlights/README.md (top 10 by 12-month score) and the
coverage table in the root README.md from report front matter.

Usage:
    python3 scripts/update_index.py          # rewrite both files
    python3 scripts/update_index.py --check  # exit 1 if either file is out of date

Only the latest report per ticker counts. Reports live at
<Sector>/<Size-tier>/<TICKER>/<TICKER>-YYYY-MM-DD.md and start with a
front-matter block (see CLAUDE.md for the fields).
"""
import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
HIGHLIGHTS = ROOT / "Highlights" / "README.md"
README = ROOT / "README.md"
TOP_N = 10
STALE_DAYS = 90

SECTORS = {
    "Communication-Services", "Consumer-Discretionary", "Consumer-Staples", "Energy",
    "Financials", "Health-Care", "Industrials", "Information-Technology", "Materials",
    "Real-Estate", "Utilities",
}
TIERS = {"1-Micro-Cap", "2-Small-Cap", "3-Mid-Cap", "4-Large-Cap", "5-Mega-Cap"}
REQUIRED = ("ticker", "company", "sector", "size_tier", "analysis_date", "price",
            "score_12m", "rating_12m", "score_5y", "rating_5y", "snowflake")
REPORT_NAME = re.compile(r"^([A-Z0-9.\-]+)-(\d{4}-\d{2}-\d{2})\.md$")
START, END = "<!-- coverage:start -->", "<!-- coverage:end -->"
CURRENCY_PREFIX = {"USD": "$", "AUD": "A$", "CAD": "C$", "GBP": "£", "EUR": "€"}  # optional `currency` field, default USD


def rating(score):
    for limit, name in ((20, "Strong Sell"), (40, "Sell"), (60, "Hold"), (80, "Buy")):
        if score <= limit:
            return name
    return "Strong Buy"


def front_matter(path):
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError("missing front matter")
    block = text[4:text.index("\n---", 4)]
    meta = {}
    for line in block.splitlines():
        if line.strip():
            key, _, value = line.partition(":")
            meta[key.strip()] = value.strip()
    return meta


def load_reports():
    latest, errors = {}, []
    for path in sorted(ROOT.glob("*/*/*/*.md")):
        rel = path.relative_to(ROOT)
        sector, tier, ticker_dir, name = rel.parts
        m = REPORT_NAME.match(name)
        if sector not in SECTORS or not m:
            continue
        try:
            meta = front_matter(path)
            missing = [k for k in REQUIRED if k not in meta]
            if missing:
                raise ValueError(f"missing fields: {', '.join(missing)}")
            checks = {
                "sector": (meta["sector"], sector), "size_tier": (meta["size_tier"], tier),
                "ticker": (meta["ticker"], ticker_dir), "analysis_date": (meta["analysis_date"], m.group(2)),
            }
            for key, (value, expected) in checks.items():
                if value != expected:
                    raise ValueError(f"{key} '{value}' does not match path ('{expected}')")
            if tier not in TIERS:
                raise ValueError(f"unknown size tier folder '{tier}'")
            for horizon in ("12m", "5y"):
                score = int(meta[f"score_{horizon}"])
                meta[f"score_{horizon}"] = score
                if meta[f"rating_{horizon}"] != rating(score):
                    raise ValueError(f"rating_{horizon} should be '{rating(score)}' for score {score}")
        except ValueError as exc:
            errors.append(f"{rel}: {exc}")
            continue
        meta["path"] = rel.as_posix()
        meta["date"] = date.fromisoformat(meta["analysis_date"])
        current = latest.get(meta["ticker"])
        if current is None or meta["date"] > current["date"]:
            latest[meta["ticker"]] = meta
    return list(latest.values()), errors


def label(folder):
    return folder.split("-", 1)[1] if folder[0].isdigit() else folder.replace("-", " ")


def rank(reports):
    return sorted(reports, key=lambda r: (-r["score_12m"], -r["score_5y"], -r["date"].toordinal(), r["ticker"]))


def render_highlights(reports, today):
    top = rank(reports)[:TOP_N]
    lines = [
        "# Highlights: Top 10 by 12-Month Score",
        "",
        "<!-- Generated by scripts/update_index.py. Do not edit by hand. -->",
        "",
        "Stocks are ranked purely by their **12-month investment score**, across all sectors and sizes.",
        "Only each stock's latest report counts. This folder holds no copies of reports. Follow the location link to read the full analysis.",
        "",
        f"**Slots filled:** {len(top)} of {TOP_N} · **Stocks covered:** {len(reports)}",
        "",
        "| Rank | Ticker | Company | 12-month score | Rating | Analysis date | Location |",
        "|---|---|---|---|---|---|---|",
    ]
    for i, r in enumerate(top, 1):
        age = (today - r["date"]).days
        when = r["analysis_date"] + (f" ⚠️ {age} days old" if age > STALE_DAYS else "")
        location = f"[{r['path']}](../{r['path']})"
        lines.append(f"| {i} | **{r['ticker']}** | {r['company']} | {r['score_12m']}/100 | {r['rating_12m']} | {when} | {location} |")
    if not top:
        lines.append("| | | No reports yet | | | | |")
    lines += [
        "",
        "Ties are broken by the 5-year score, then by the most recent analysis.",
        f"⚠️ marks a report older than {STALE_DAYS} days. Its 12-month view may be out of date and is worth refreshing.",
        "Rating bands: 1–20 Strong Sell · 21–40 Sell · 41–60 Hold · 61–80 Buy · 81–100 Strong Buy.",
        "",
    ]
    return "\n".join(lines)


def render_coverage(reports):
    rows = sorted(reports, key=lambda r: (r["sector"], r["size_tier"], r["ticker"]))
    lines = [
        START,
        "| Ticker | Company | Sector | Size | Analysis date | Price | Base fair value | 12-month score | 5-year score | Snowflake |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in rows:
        cur = CURRENCY_PREFIX.get(r.get("currency", "USD"), r.get("currency", "") + " ")
        fv = f"{cur}{r['fair_value_base']}" if r.get("fair_value_base") else "—"
        lines.append(
            f"| [{r['ticker']}]({r['path']}) | {r['company']} | {label(r['sector'])} | {label(r['size_tier'])} "
            f"| {r['analysis_date']} | {cur}{r['price']} | {fv} | {r['score_12m']}, {r['rating_12m']} "
            f"| {r['score_5y']}, {r['rating_5y']} | {r['snowflake']} |"
        )
    lines.append(END)
    return "\n".join(lines)


def main():
    check = "--check" in sys.argv[1:]
    reports, errors = load_reports()
    if errors:
        print("Report errors:\n  " + "\n  ".join(errors), file=sys.stderr)
        sys.exit(2)

    readme = README.read_text(encoding="utf-8")
    if START not in readme or END not in readme:
        print(f"README.md is missing the {START} / {END} markers", file=sys.stderr)
        sys.exit(2)
    new_readme = readme[:readme.index(START)] + render_coverage(reports) + readme[readme.index(END) + len(END):]

    old_highlights = HIGHLIGHTS.read_text(encoding="utf-8") if HIGHLIGHTS.exists() else ""
    new_highlights = render_highlights(reports, date.today())

    stale = [p for p, new, old in ((HIGHLIGHTS, new_highlights, old_highlights), (README, new_readme, readme)) if new != old]
    if check:
        if stale:
            print("Out of date: " + ", ".join(str(p.relative_to(ROOT)) for p in stale) + ". Run python3 scripts/update_index.py")
            sys.exit(1)
        print("Highlights and coverage table are up to date.")
        return
    HIGHLIGHTS.parent.mkdir(exist_ok=True)
    HIGHLIGHTS.write_text(new_highlights, encoding="utf-8")
    README.write_text(new_readme, encoding="utf-8")
    ranked = rank(reports)
    print(f"{len(reports)} stock(s) indexed. Top {min(TOP_N, len(reports))}: " +
          ", ".join(f"{r['ticker']} ({r['score_12m']})" for r in ranked[:TOP_N]))


if __name__ == "__main__":
    main()
